---
title: "Data coverage"
author: "Koen Hufkens"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data coverage}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r include=FALSE}
library(tidyverse)
library(mapview)
library(leaflet)
library(leafpop)
library(sf)

sites <- readRDS("../data/flux_data_kit_site-info.rds") %>%
  select(-date_start,-date_end,-koeppen_code_beck) %>%
  rename(
    'koeppen' = 'koeppen_code',
    'start' = 'year_start',
    'end' = 'year_end',
    'IGBP' = 'igbp_land_use'
  )
```

<center>
```{r echo = FALSE}
leaflet(sites) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addMarkers(~lon, ~lat, label = ~sitename, popup = popupTable(sites))
```
</center>
<br><br>

The below table lists all sites, for which we also provide a [CSV file](https://github.com/computationales/flux_data_kit/raw/main/data/flux_data_kit_site-info.csv). In the table below we list the FLUXNET abbreviation of all sites, their geographic location and elevation, the source of the data (icos, fluxnet2015, oneflux, plumber), the Koeppen-Geiger code, start and end year, water holding capacity (whc) and IGBP land cover class.

---

```{r echo = FALSE}
knitr::kable(sites)
```
