---
title: "Cleaning by Ziyu"
author: "Ziyu and Beni"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lubridate)
```

```{r}
site_based_drivers_HH <- readRDS("../data/site_based_drivers_HH.rds")

df <- site_based_drivers_HH %>% 
  group_by(sitename) %>% 
  nest()

allsites <- site_based_drivers_HH$sitename %>% unique()

#need:sitename, gpp?
#1.predealing
source("../R/clean_fluxdata_functions.R")

# dealing with the data first convert into daily by taking mean
ddf <- df %>% 
  mutate(data = purrr::map2(sitename, data, ~agg_to_daily(.y, site = .x)))
```


```{r}
#add outliers
dat2 <- add_outliers(mydata = dat1)
```


```{r}

#add drift detection
dat3 <- add_drift(mydata = dat2)
```


```{r}
#add spurious data
dat4 <- add_spurious(mydata = dat3)
```


```{r}
#add the growing seasons
dat5 <- GrowingSeason(mydata = dat4)
```


```{r}
##add step change detection, but create a different dataset because use the monthly data
#should add into the initial dataset as well?
dat6 <- add_step_change(mydata = dat5)


dat.0 <- nrow(site_based_drivers_HH %>% filter(sitename == "SE-Nor"))
dat.1 <- table(is.na(dat1$gpp))#has 9 NA value for all 2554 data
dat.2 <- table(dat2$outline)#has 113 outliers for all 2546 data
#dat.3 <- how to show the drift?
dat.4 <- table(dat4$rep)#has all 0 rep for the 2554 data
dat.5 <- table(dat5$is_growing_season)#348 not for growing seasons out of 2546
dat.6 <- table(dat6$SCpoint)#13 possible step change points

#visualize NAs,for dat1
ggplot(data = dat1, aes(x = date, y = gpp))+
  geom_point()
#after this step, we have 
#visualize outliers, for dat2
ggplot(data = dat2, aes(x = date, y = res))+
  geom_point(aes(color = outline))
#visualize drift, for dat3
ggplot(data = dat3, aes(x = date, y = tfordrift))+
  geom_point()
#visualize spurious data, for dat4
ggplot(data = dat4, aes(x = date, y = gpp))+
  geom_point(aes(color = rep))
#visualize growing season
ggplot(data = dat5, aes(x = date, y = gpp))+
  geom_point(aes(color = is_growing_season))
#visualize step change detection
ggplot(data = dat6, aes(x = month_dec, y = gpp))+
  geom_point(aes(color = factor(SCpoint)))
```
